[package]
name = "sixteen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-iter = "1.1.1"
pathfinding = "4.1.1"
peg = "0.8.1"
